import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/index.scss"
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div style={{display:"flex",flexDirection:"column",height:"100vh",width:"100vw",overflowX:"hidden"}}>
     
      <Header/>
      {children}
      <ToastContainer/>
      
       </div>
      </body>
    </html>
  );
}
